services:
  - type: web
    name: book-dashboard-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: AUTH0_DOMAIN
        value: ak23-dev.us.auth0.com  
      - key: AUTH0_AUDIENCE
        value: https://book-dashboard-api
      - key: DATABASE_PATH
        value: ./database.sqlite
      - key: FRONTEND_URL
        value: http://localhost:5173,https://book-das.netlify.app,https://book-dashboard-hhxb.onrender.com